# dubbo client yaml configure file

#*bool  `yaml:"check"  json:"check,omitempty" property:"check"`
check: true

# client
#string `yaml:"request_timeout" default:"5s" json:"request_timeout,omitempty" property:"request_timeout"`
request_timeout: "10s"

# connect timeout
#`default:"100ms"  yaml:"connect_timeout" json:"connect_timeout,omitempty" property:"connect_timeout"`
Connect_Timeout: "3s"

# application config
application:
  organization: "dubbogo"
  name: "dubbo-go-proxy"
  module: "dubbo-go-proxy"
  version: "1.0.0"
  group: "test"
  owner: "dqc13215"
  environment: "dev"

#`default:"{}" yaml:"registries" json:"registries" property:"registries"`
registries:
  #RegistryConfig is the configuration of the registry center
  "zk_1":
    protocol: "zookeeper"
    timeout: "3s"
    address: "10.100.156.17:2181"
    username: ""
    password: ""
    #group:               #string
    #ttl:                 #string
    #simplified:          #bool
    #preferred:           #bool
    #zone:                #string
    #weight:              #int64
    #params:              #map[string]string

references:
  #context        context.Context
  #pxy            *proxy.Proxy
  #id             string
  #InterfaceName  string            `required:"true"  yaml:"interface"  json:"interface,omitempty" property:"interface"`
  #Check          *bool             `yaml:"check"  json:"check,omitempty" property:"check"`
  #Url            string            `yaml:"url"  json:"url,omitempty" property:"url"`
  #Filter         string            `yaml:"filter" json:"filter,omitempty" property:"filter"`
  #Protocol       string            `default:"dubbo"  yaml:"protocol"  json:"protocol,omitempty" property:"protocol"`
  #Registry       string            `yaml:"registry"  json:"registry,omitempty"  property:"registry"`
  #Cluster        string            `yaml:"cluster"  json:"cluster,omitempty" property:"cluster"`
  #Loadbalance    string            `yaml:"loadbalance"  json:"loadbalance,omitempty" property:"loadbalance"`
  #Retries        string            `yaml:"retries"  json:"retries,omitempty" property:"retries"`
  #Group          string            `yaml:"group"  json:"group,omitempty" property:"group"`
  #Version        string            `yaml:"version"  json:"version,omitempty" property:"version"`
  #ProvideBy      string            `yaml:"provide_by"  json:"provide_by,omitempty" property:"provide_by"`
  #Methods        []*MethodConfig   `yaml:"methods"  json:"methods,omitempty" property:"methods"`
  #Async          bool              `yaml:"async"  json:"async,omitempty" property:"async"`
  #Params         map[string]string `yaml:"params"  json:"params,omitempty" property:"params"`
  #invoker        protocol.Invoker
  #urls           []*common.URL
  #Generic        bool   `yaml:"generic"  json:"generic,omitempty" property:"generic"`
  #Sticky         bool   `yaml:"sticky"   json:"sticky,omitempty" property:"sticky"`
  #RequestTimeout string `yaml:"timeout"  json:"timeout,omitempty" property:"timeout"`
  #ForceTag       bool   `yaml:"force.tag"  json:"force.tag,omitempty" property:"force.tag"`

protocol_conf:
  dubbo:
    reconnect_interval: 0
    connection_number: 2
    heartbeat_period: "30s"
    session_timeout: "360s"
    fail_fast_timeout: "5s"
    pool_size: 4
    pool_ttl: 600
    # gr_pool_size is recommended to be set to [cpu core number] * 100
    gr_pool_size: 200
    # queue_len is recommended to be set to 64 or 128
    queue_len: 64
    # queue_number is recommended to be set to gr_pool_size / 20
    queue_number: 10
    getty_session_param:
      compress_encoding: false
      tcp_no_delay: true
      tcp_keep_alive: true
      keep_alive_period: "120s"
      tcp_r_buf_size: 262144
      tcp_w_buf_size: 65536
      pkg_rq_size: 1024
      pkg_wq_size: 512
      tcp_read_timeout: "1s"  #1
      tcp_write_timeout: "5s" #5
      wait_timeout: "5s"
      max_msg_len: 10240000
      session_name: "client"

#filter:

#filter_conf:

#shutdown_conf:

#config_type:

#configCenter:
  #protocol: zookeeper      #string `required:"true"  yaml:"protocol"  json:"protocol,omitempty"`
  #address: "10.100.156.17:2181"       #string `yaml:"address" json:"address,omitempty"`
  #cluster: "failover"       #string `yaml:"cluster" json:"cluster,omitempty"`
  #group: "dubbo"         #string `default:"dubbo" yaml:"group" json:"group,omitempty"`
  #username:       #string `yaml:"username" json:"username,omitempty"`
  #password:       #string `yaml:"password" json:"password,omitempty"`
  #log_dir:        #string `yaml:"log_dir" json:"log_dir,omitempty"`
  #config_file    #string `default:"dubbo.properties" yaml:"config_file"  json:"config_file,omitempty"`
  #namespace:     #string `default:"dubbo" yaml:"namespace"  json:"namespace,omitempty"`
  #app_config_file #string `default:"dubbo.properties" yaml:"app_config_file"  json:"app_config_file,omitempty"`
  #app_id         #string `default:"dubbo" yaml:"app_id"  json:"app_id,omitempty"`
  #timeout    #string `yaml:"timeout"  json:"timeout,omitempty"`
  #remote_ref     #string `required:"false"  yaml:"remote_ref"  json:"remote_ref,omitempty"`