---
static_resources:
  listeners:
    - name: "net/http"
      address:
        socket_address:
          protocol_type: "HTTP"                     #[HTTP/TCP/UDP]
          address: "0.0.0.0"
          port: 8888
          #resolver_name:""
      filter_chains:
        - filter_chain_match:
            domains:
              - api.dubbo.com
              - api.proxy.com
          filters:
            - name: dgp.filters.http_connect_manager
              config:
                route_config:
                  routes:
                    - match:
                        prefix: "/api/v1"
                        headers:
                          - name: "X-DGP-WAY"
                            value: "dubbo"
                      route:
                        cluster: "test_dubbo"
                        cluster_not_found_response_code: 505
                        cors:
                          allow_origin:
                            - "*"
                          enabled: true
                http_filters:
                  - name: dgp.filters.http.api
                    config:
                  - name: dgp.filters.http.router
                    config:
                  - name: dgp.filters.http_transfer_dubbo
                    config:
                server_name: "test_http_dubbo"
                generate_request_id: false
      config:
        idle_timeout: 5s
        read_timeout: 5s
        write_timeout: 5s
  clusters:
    - name: "test_dubbo"
      #type: ""               #[Static/StrictDNS/LogicalDns/EDS/OriginalDst]
      lb_policy: "RoundRobin"         #[RoundRobin/IPHash/WightRobin/Rand]
      connect_timeout: "5s"
      request_timeout: "10s"
      #hosts:
        #socket_address:
        #  - protocol_type:              #[HTTP/TCP/UDP]
        #    address:
        #    port:
        #    resolver_name:
      #health_checks:
      #  - host: ""
      #    path: ""
      #    usehttp2: false
      #    expectedstatuses: 200
      registries:
        "zookeeper":
          - timeout: "3s"
            address: "10.100.156.17:2181"
            username: ""
            password: ""
      #eds_cluster_config:
      #  service_name: ""
      #  eds_config:
      #    path:
      #    api_config_source:
      #      api_type:                   #[REST/GRPC、DUBBO]
      #      cluster_name: test_dubbo;test_dubbo1

  shutdown_config:
    timeout: "60s"
    step_timeout: "10s"
    reject_policy: "immediacy"

#dynamic_resources:


#tracing:
#  http:
#    name:
#    config: